---
image: "buluma/github-action-molecule:4.0.6"

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1

molecule:
  script:
    - image=${image} tag=${tag} molecule test
  retry: 1
  parallel:
    matrix:
      - image: "alpine-openrc"
        tag: "latest"
      - image: "debian-systemd"
        tag: "latest"
      - image: "debian-systemd"
        tag: "bookworm"
      - image: "enterpriselinux"
        tag: "latest"
      - image: "fedora-systemd"
        tag: "34"
      - image: "fedora-systemd"
        tag: "latest"
      - image: "opensuse"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"

testing:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "testing"
  retry: 1
  parallel:
    matrix:
      - image: "alpine-openrc"
        tag: "latest"
      - image: "debian-systemd"
        tag: "latest"
      - image: "debian-systemd"
        tag: "bookworm"
      - image: "enterpriselinux"
        tag: "latest"
      - image: "fedora-systemd"
        tag: "34"
      - image: "fedora-systemd"
        tag: "latest"
      - image: "opensuse"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"

galaxy:
  script:
    - ansible-galaxy role info buluma.victoria_metrics

role_testing:
  script:
    - image=${image} tag=${tag} ansible-galaxy install buluma.victoria_metrics
  retry: 1
  parallel:
    matrix:
      - image: "alpine-openrc"
        tag: "latest"
      - image: "debian-systemd"
        tag: "latest"
      - image: "debian-systemd"
        tag: "bookworm"
      - image: "enterpriselinux"
        tag: "latest"
      - image: "fedora-systemd"
        tag: "34"
      - image: "fedora-systemd"
        tag: "latest"
      - image: "opensuse"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"
